version: '3'

services:
  node_app:
    container_name: node_container
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongodb
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"

